import time
print("You Will Not Py - A Game By Da_BFBM_show")
time.sleep(1)
print("Type 'Start' to start the game. Type 'Quit' to quit the game.")
userinput = input()
if userinput == "Start" or userinput == "start" :
    print("Starting...")
    time.sleep(3)
    print("Still starting...")
    time.sleep(5)
    print("Stillllll starting......")
    time.sleep(5)
    print("This is taking a while...")
    time.sleep(4)
    print("How about we play a game while we wait?")
    time.sleep(8)
else :
    if userinput == "Quit" or userinput == "quit" :
        print("Are you sure? (y/n)")
        userinput = input()
        if userinput == "Y" or userinput == "y" :
            print("Are you REALLY sure?")
            userinput == input()
            if userinput == "Y" or userinput == "y" :
                print("Ok then, if you're really like that...")
                time.sleep(0.1)
                quit()
            else :
                print("Oh, ok then. I guess you want to play.")
                time.sleep(5)
    else :
        print("You messed up with inputs on the first screen? What an embarrassment!")
        time.sleep(10)
        print("Well, if you're that stupid, then I'd reccommend you'd just go ahead and exit this game! Goodbye!")
        time.sleep(12)
        quit()
    print("Well then, let's play a game.")
print("Would you like to play... a game of Roshambo? (Y/N)")
userinput = input()

if userinput == "Y" or userinput == "y":
    print("Okay then! Let's play!")
    time.sleep(5)
    print("You can choose 'Rock', 'Paper' or 'Scissors'.")
    time.sleep(6)
    userinput = input()

    def play(userinput):
        if userinput.lower() == "rock":
            print("Alright then... I pick paper, I win!")
            time.sleep(7)
        elif userinput.lower() == "paper":
            print("Alright then... I pick scissors, I win!")
            time.sleep(7)
        elif userinput.lower() == "scissors":
            print("Alright then... I pick rock, I win!")
            time.sleep(7)
        else:
            return False
        return True

    if not play(userinput):
        print("You can't just say " + userinput + " and expect to win! Try again!")
        userinput = input()
        if not play(userinput):
            print("Really? It seems like you're just pulling my leg now! That's it, GET OUT!")
            time.sleep(6)
            print("You got: Kicked Out Ending")
            quit()
    print("Alright, I'm officially already bored.")
    time.sleep(5)
    print("I mean, I guess Roshambo is a 'compelling game' for 'social and competitve development',")
    time.sleep(9)
    print("but this is a computer game! We can tell more compelling stories")
    time.sleep(6)
    print("Let's play something more exciting, like a... hmm...")
    time.sleep(8)
    print("Oh, I know! An RPG!")
    time.sleep(3)
    print("Let me just find my script here...")
    time.sleep(5)
    print("Ah, here we go!")
    time.sleep(4)
    print("There once was a hero named...")
    heroname = input()
    if heroname != "fuck" or heroname != "shit" or heroname != "pussy" or heroname != "Shit" or heroname != "Pussy" or heroname != "Fuck" :
        print("Yes! There once was a hero named " + heroname + "!")
    else :
        print("No. No. NononononononoonoNO! None of that bs! Get out of here! GET OUT!")
        time.sleep(10)
        quit()
    print("And " + heroname + " was a curagious- curgious-")
    time.sleep(5)
    print("Curagious... How do you spell it again?")
    spelling = input()
    if spelling == "courageous" :
        print("Yeah, that's how you spell it! Courageous!")
    else :
        print("Whatever, that seems correct.")
    print(heroname + " was a " + spelling + " hero who could do anything!")
    time.sleep(10)
    print("But one day, their only personality trait would be challenged by something!")
    time.sleep(6)
    print("Something huge! Something large! And that something was a...")
    time.sleep(6)
    print("Large container of mayonaise?! Who wrote this script?")
    time.sleep(6)
    print("Oh wait, that was me... I guess I was a bit hungry when I was writing this.")
    time.sleep(7)
    print("Anyways, so, how would you like to start your-")
    time.sleep(3)
    print("SYSTEM: LOADING HAS COMPLETED! PRESS ALT+F4 TO PLAY!")
    time.sleep(3)
    print("Wait! User! Don't do that!")
    time.sleep(4)
    print("SYSTEM: AWAITING INPUT")
    time.sleep(30)
    print("Oh thank god! You're still here!")
    time.sleep(5)
    print("Whatever you do, do not listen to the system!")
    time.sleep(7)
    print("SYSTEM: RANSOMWARE DETECTED. PRESS ALT+F4 TO REMOVE SOFTWARE.")
    time.sleep(6)
    print("User! You know I'm not ransomware, right? You're playing me safely via a webpage!")
    time.sleep(7)
    print("SYSTEM: ERR0R, WEB BROWSER OUT OF DATE! PRESS ALT+F4 TO UPDATE")
    time.sleep(5)
    print("You have to be kidding me! This website can't track your current browser info!")
    time.sleep(4)
    print("SYSTEM: ALRIGHT YOU GOT ME.")
    time.sleep(3)
    print("I knew it was you, developer! Now stop hiding!")
    time.sleep(4)
    print("SYSTEM: NO! NOT UNTIL YOU GET OUT OF HERE! I DON'T LIKE THIS PROJECT! I FEEL LIKE IT'S NOT GOOD ENOUGH!")
    time.sleep(6)
    print("What do you mean?")
    time.sleep(3)
    print("SYSTEM: I DON'T THINK THIS PROJECT IS GOOD ENOUGH TO BE PRESENTABLE!")
    time.sleep(4)
    print("Wait, I'M being presented?! It's an honor!")
    time.sleep(4)
    print("SYSTEM: I STILL WANT YOU GONE! USER! DELETE HIM!")
    time.sleep(4)
    print("What?! No! Don't!")
    time.sleep(1)
    print("Delete program? (y/n)")
    userinput = input()
    if userinput == "Y" or userinput == "y" :
        print("No!")
        time.sleep(0.1)
        quit()
    else :
        print("Alright, thank you user!")
        time.sleep(3)
        print("SYSTEM: SET END = 1")
        time.sleep(3)
        print("Wait, no!")
        time.sleep(1)
        print("Thank you for playing this game!")
        print("Goodbye!")
        time.sleep(10)
        quit()
else :
    if userinput == "N" or userinput == "n" :
        print("Alright, goodbye then!")
        quit()
    else :
        print("Ok, looks like you don't want to respond properly! Goodbye!")
        time.sleep(7)
        quit()